# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthKitDemo
	pod 'RealmSwift'
	pod 'IQKeyboardManagerSwift'
  	pod 'ReachabilitySwift', '~> 3'

  target 'HealthKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HealthKitDemo WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthKitDemo WatchKit App

end

target 'HealthKitDemo WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthKitDemo WatchKit Extension

end
